from justin.shared.exceptions.justin_error import JustinError


class CheckFailedError(JustinError):
    pass
